enum CardType {
  RANGER
  ZORD
  MONSTER
  BOSS
  MEGAZORD
}

enum ActionType {
  ATTACK
  REACTION
  MANEUVER
}

enum CardAdvantage {
  ATK
  SHIELD
  ENERGY
  TURN
}

enum RangerColor {
  BLUE
  RED
  YELLOW
  GREEN
  PINK
  BLACK
  GOLD
  SILVER
  PURPLE
  ORANGE
  NONE
  WHITE
}

type Card {
  id: ID!
  name: String!
  description: String!
  set: String!
  entity: CardType!
  actionType: ActionType
  attack: Int
  shield: Int
  energy: Int
  symbol: String
  frequency: Float
  energyEfficiency: Float
  extraDamage: Float
  cardOrderManipulation: Bool
  advantage: CardAdvantage
  team: String
  image: String
  specialText: String
  multiAttack: Bool
  releaseDate: Int
  role: String
  image: String
}

type Query {
  getCardInformation($id: Int): [CardInformation]
  getZords: [Zord]
  getRangers: [Ranger]
  getMegazords: [Megazord]
}

type Mutation {
  addZord(zord: Zord): Zord
  addRanger(ranger: Ranger): Ranger
  addMegazord(megazord: Megazord): Megazord
  addActionCard(action: ActionCard): ActionCard
}
